//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadsOfRussia_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdType { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<int> IdEmployee { get; set; }
        public string Other { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual StatusEvents StatusEvents { get; set; }
        public virtual TypeEvents TypeEvents { get; set; }
    }
}
