//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadsOfRussia_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Files()
        {
            this.Librarys = new HashSet<Librarys>();
            this.СardofMaterials = new HashSet<СardofMaterials>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Storage { get; set; }
        public string Comment { get; set; }
        public Nullable<int> IdCategory { get; set; }
        public Nullable<int> IdSatus { get; set; }
    
        public virtual CategoryFiles CategoryFiles { get; set; }
        public virtual StatusFiles StatusFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Librarys> Librarys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СardofMaterials> СardofMaterials { get; set; }
    }
}
