//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadsOfRussia_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сalendars
    {
        public int Id { get; set; }
        public System.DateTime Strart_Day { get; set; }
        public System.DateTime End_Day { get; set; }
        public string Reason { get; set; }
        public int Id_Employee { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
