//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadsOfRussia_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class СardofMaterials
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DateAssent { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> IdType { get; set; }
        public string Area { get; set; }
        public int IdEmloyee { get; set; }
        public Nullable<int> IdFile { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Files Files { get; set; }
        public virtual StatusMaterials StatusMaterials { get; set; }
        public virtual TypeMaterials TypeMaterials { get; set; }
    }
}
